### ISSUE TITLE
Is it possible to create a keyspace while applying migrations?

### ISSUE THREAD

**Issue by pluskal** [simpleidserver/EFCore.Cassandra#10]
When I try to apply migration or create a database using
```

using (var dbContext = new FakeDbContext())
        {
          dbContext.Database.Migrate();
// OR
          dbContext.Database.EnsureCreated();
        }
```
when a keyspace does not exist, I am getting an exception.

Would it make sense to extend the implementation of `DatabaseFacade` methods `EnsureCreated, Migrate` and async variants to create keyspace when it does not exist?

**Comment by simpleidserver** [comment]
The issue is fixed in the branch "release/2.0.3".
