### ISSUE TITLE
Query with specified condition.

### ISSUE THREAD

**Issue by SinDotBe** [simpleidserver/EFCore.Cassandra#3]
In EFCore.Cassandra.Samples, This query 
` int k = 10;
  var d = dbContext.Applicants.Where(d => d.Decimal == k);`
encounters such an error:
`line 3:19 no viable alternative at character '_'`
thanks!

**Comment by simpleidserver** [comment]
The problem is fixed in the branch "release/2.0.0".
We are doing some investigation to understand why it's not possible to filter on **GUID**.

**Comment by simpleidserver** [comment]
The issue is fixed in the release 2.0.0.

**Comment by SinDotBe** [comment]
thanks a lot
