### ISSUE TITLE
add-migration error in "release/2.0.0"

### ISSUE THREAD

**Issue by SinDotBe** [simpleidserver/EFCore.Cassandra#7]
I have received
"The current CSharpHelper cannot scaffold literals of type 'Microsoft.EntityFrameworkCore.CassandraClusteringOrderByOption'. Configure your services to use one that can".

when set 
`            modelBuilder.Entity<Applicant>().ForCassandraSetClusteringOrderBy(new[]
                {
                    new CassandraClusteringOrderByOption("Id", CassandraClusteringOrderByOptions.ASC)
                });`

in OnModelCreating.

**Comment by simpleidserver** [comment]
The migration error is fixed : https://github.com/simpleidserver/medikit/commit/cf338406afdb03c410fbc5e8edc096cf2d72f93f

In the *Applicant* table, the *id* column is defined as a partition key.

You should use *Order* column because it's defined as a cluster column.
