### ISSUE TITLE
Q: Is UDT supported?

### ISSUE THREAD

**Issue by pluskal** [simpleidserver/EFCore.Cassandra#9]
Is UDT supported, or do you plan to add support for it in the future? I looked at the source but was unable to find any `modelBuilder` extensions that would create UDTs in Cassandra.

**Comment by simpleidserver** [comment]
Hi,

UDT is not yet supported. This features can be included for the next release

**Comment by simpleidserver** [comment]
The feature has been implemented in the releaase 2.0.2.
You can find an example here : https://github.com/simpleidserver/EFCore.Cassandra/blob/master/samples/EFCore.Cassandra.Samples/Program.cs

The "ApplicantAddress" is a UserDefinedType.

**Comment by pluskal** [comment]
Thanks! Works very well!
